url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: The Gonios
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Team names, titles and social links
people:
- name: Clara Scherrer
  pic: Clara
  position: surname
  alt: Clara picture
  social:
    - title: github
      url: #
    - title: linkedin
      url: #
      
- name: Nathan Decurnex
  pic: Nathan
  position: surname
  alt: Nathan picture
  social:
    - title: github
      url: #
    - title: linkedin
      url: #

- name: Noémie Chillier
  pic: Noémie
  position: surname
  alt: Noémie picture
  social:
    - title: github
      url: #
    - title: linkedin
      url: #

- name: Thibaut Hennel
  pic: Thibaut
  position: surname
  alt: Thibaut picture
  social:
    - title: github
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

#DLAB
dlab: https://dlab.epfl.ch/
ada: https://dlab.epfl.ch/teaching/fall2022/cs401/
bob: https://people.epfl.ch/robert.west
epfl: https://www.epfl.ch/en/

#data
corpus: http://www.cs.cmu.edu/~ark/personas/
paper: http://www.cs.cmu.edu/~dbamman/pubs/pdf/bamman+oconnor+smith.acl13.pdf

# Postal address (add as many lines as necessary)
address:
  - line: École Polytechnique Fédérale de Lausanne
  - line: Rte des Noyerettes, 1015 Ecublens
  - line: MED building

# Build settings
markdown: kramdown
permalink: pretty